### ISSUE TITLE
Installing Ensembl release fails at reading GTF step

### ISSUE THREAD

**Issue by maximz** [openvax/pyensembl#195]
I'm rebuilding a Docker image I've maintained for a while. This specific line hasn't changed in months, but today no longer works:

```
docker run -it jupyter/datascience-notebook:400c69639ea5 bash
> pip install pyensembl
...
> pyensembl install --release 79 --species homo_sapiens
2018-01-11 05:19:28,769 - pyensembl.shell - INFO - Running 'install' for EnsemblRelease(release=79, species='homo_sapiens')
2018-01-11 05:19:28,770 - pyensembl.download_cache - INFO - Fetching /home/jovyan/.cache/pyensembl/GRCh38/ensembl79/Homo_sapiens.GRCh38.79.gtf.gz from URL ftp://ftp.ensembl.org/pub/release-79/gtf/homo_sapiens/Homo_sapiens.GRCh38.79.gtf.gz
2018-01-11 05:19:28,770 - datacache.download - INFO - Downloading ftp://ftp.ensembl.org/pub/release-79/gtf/homo_sapiens/Homo_sapiens.GRCh38.79.gtf.gz to /home/jovyan/.cache/pyensembl/GRCh38/ensembl79/Homo_sapiens.GRCh38.79.gtf.gz
2018-01-11 05:20:10,861 - pyensembl.download_cache - INFO - Fetching /home/jovyan/.cache/pyensembl/GRCh38/ensembl79/Homo_sapiens.GRCh38.cdna.all.fa.gz from URL ftp://ftp.ensembl.org/pub/release-79/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
2018-01-11 05:20:10,861 - datacache.download - INFO - Downloading ftp://ftp.ensembl.org/pub/release-79/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz to /home/jovyan/.cache/pyensembl/GRCh38/ensembl79/Homo_sapiens.GRCh38.cdna.all.fa.gz
2018-01-11 05:21:05,860 - pyensembl.download_cache - INFO - Fetching /home/jovyan/.cache/pyensembl/GRCh38/ensembl79/Homo_sapiens.GRCh38.pep.all.fa.gz from URL ftp://ftp.ensembl.org/pub/release-79/fasta/homo_sapiens/pep/Homo_sapiens.GRCh38.pep.all.fa.gz
2018-01-11 05:21:05,860 - datacache.download - INFO - Downloading ftp://ftp.ensembl.org/pub/release-79/fasta/homo_sapiens/pep/Homo_sapiens.GRCh38.pep.all.fa.gz to /home/jovyan/.cache/pyensembl/GRCh38/ensembl79/Homo_sapiens.GRCh38.pep.all.fa.gz
2018-01-11 05:21:18,929 - pyensembl.database - INFO - Creating database: /home/jovyan/.cache/pyensembl/GRCh38/ensembl79/Homo_sapiens.GRCh38.79.gtf.db
2018-01-11 05:21:18,930 - pyensembl.gtf - INFO - Reading GTF from /home/jovyan/.cache/pyensembl/GRCh38/ensembl79/Homo_sapiens.GRCh38.79.gtf.gz
Killed
> echo $?
137
```

All installed package versions from `pip freeze`:

```
alembic==0.9.6
appdirs==1.4.3
asn1crypto==0.22.0
backports.functools-lru-cache==1.4
beautifulsoup4==4.5.3
biopython==1.70
bleach==2.0.0
bokeh==0.12.13
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
click==6.7
cloudpickle==0.2.2
conda==4.3.29
cryptography==2.0.3
cycler==0.10.0
Cython==0.25.2
dask==0.16.0
datacache==0.4.20
decorator==4.1.2
dill==0.2.6
distributed==1.20.2
entrypoints==0.2.3
fastcache==1.0.2
gtfparse==0.0.6
h5py==2.6.0
heapdict==1.0.0
html5lib==1.0.1
idna==2.6
ipykernel==4.7.0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.0.5
jedi==0.10.2
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-core==4.4.0
jupyterhub==0.8.1
jupyterlab==0.30.6
jupyterlab-launcher==0.6.0
llvmlite==0.16.0
locket==0.2.0
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.1
memoized-property==1.0.3
mistune==0.8.3
mock==2.0.0
msgpack-python==0.4.8
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
notebook==5.2.2
numba==0.31.0
numexpr==2.6.4
numpy==1.12.1
olefile==0.44
pamela==0.3.0
pandas==0.19.2
pandocfilters==1.4.1
partd==0.3.8
patsy==0.4.1
pbr==3.1.1
pexpect==4.3.0
pickleshare==0.7.4
Pillow==4.3.0
progressbar33==2.4
prompt-toolkit==1.0.15
protobuf==3.5.1
psutil==5.4.0
ptyprocess==0.5.2
pycosat==0.6.2
pycparser==2.18
pyensembl==1.1.0
Pygments==2.2.0
pyOpenSSL==17.2.0
pyparsing==2.2.0
PySocks==1.6.7
python-dateutil==2.6.1
python-editor==1.0.3
python-oauth2==1.0.1
pytz==2017.3
PyYAML==3.12
pyzmq==16.0.2
requests==2.18.4
rpy2==2.8.5
ruamel-yaml==0.11.14
scikit-image==0.12.3
scikit-learn==0.18.2
scipy==0.19.1
seaborn==0.7.1
serializable==0.1.1
simplegeneric==0.8.1
simplejson==3.13.2
singledispatch==3.4.0.3
six==1.11.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.13
statsmodels==0.8.0
sympy==1.0
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
tinytimer==0.0.0
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
typechecks==0.0.2
urllib3==1.22
vincent==0.4.4
wcwidth==0.1.7
webencodings==0.5
widgetsnbextension==3.1.0
xlrd==1.1.0
zict==0.1.3
```

Same error occurs when I run on the `jupyter/datascience-notebook:8f56e3c47fec` image, which is a few months old. So it's unlikely that background changes in the docker image I'm using are the culprit.

That doesn't acquit pyensembl's dependencies that weren't baked into either version of the docker image. Those would be: `typechecks`, `datacache`, `memoized-property`, **`gtfparse`**, `serializable`, `tinytimer`. pip grabbed these for me today when I went to install pyensembl.

**Comment by bbreton** [comment]
Hello,

I'm not one of the authors, but I think I know what the problem is.

Killed like that in the text usually means the process was killed by the OS most likely due to being out of memory though I believe depending on kernel configuration a similar message also can be seen if cpu is exhausted.

I would recommend hunting down the OS logs which if it was the OOM memory killer will have a log of it.  I'm not 100% certain if you would see the message on the host or within the docker container, but one of them should have a log of it.

I tested as far as I can tell the same as you did and it worked:
docker run -it jupyter/datascience-notebook:400c69639ea5 bash
> pip install pyensembl
> pyensembl install --release 79 --species homo_sapiens


This stack overflow thread explains further and should give you enough to debug it if I am right.
https://stackoverflow.com/questions/726690/who-killed-my-process-and-why

**Comment by iskandr** [comment]
Hey Maxim,

I'm also encountering some mysterious failures with pyensembl installs on
Travis (due to suddenly insufficient disk space). I think something must
have changed on Travis's side and we're now running on smaller instances.

Any idea how to control what size instance the unit tests run on?

--Alex

**Comment by iskandr** [comment]
We figured out that Travis switched from `precise` to `trusty` distributions, and the new image has significantly less free space. You can switch back with `dist: precise` but it only works for another month. I pushed one branch that shrinks disk usage by ~1/3-1/2 and I'm working on loading fewer columns from the GTF (which will hopefully also create a smaller database). But, unless Travis fixes the disk space on `trusty` there will be a limit to how many Ensembl releases you can install with your unit tests (probably max 2).

**Comment by maximz** [comment]
Ah thanks folks! So sorry I lost this.

Yes, exactly -- my issue was I ran into disk space and memory configuration settings that were set far lower than I thought in the Docker VM I was using.

@iskandr sorry to hear about this annoying difficulty with Travis; hope you stumble across a nicer workaround than having to rearchitect your code.

**Comment by HansCeril** [comment]
hello, 
i m actually an intern in bioinformatics, and i am working on an ETL process. Could you let me know how to use this  tool without downloaded this Docker (docker run -it jupyter/datascience-notebook:400c69639ea5 bash). When I try to download this tool using 'pip install pyensembl' i get every time this error : 'Segmentation Errors (core dumped)'
I would like to extract all ensembl data using pyensembl.
Thank you very much for you attention.
Best regards, 
Hans CERIL

**Comment by iskandr** [comment]
Hi Hans, 

I'm guessing your issue is unrelated to the failure above. I've never seen a segmentation fault from installing pyensembl. Can you tell me more about your setup (what OS, version of Python, &c). Also, can you paste a more complete error message (including any preceding lines that might give a clue about what is segfaulting where).

**Comment by HansCeril** [comment]
Hi,

thank your your response.

Concerning my problem, when i m trying to do ' pip3 install pyensembl', i get an error.

At the begining of the installation everything are ok , but at the end of the installation I get an segmentation error, and i can't use the pyensembl package.

I was may be thinking that 's could be an memory space problem ?

Best regards,

Hans


Collecting pyensembl
Collecting pandas>=0.15 (from pyensembl)
  Using cached pandas-0.22.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting six>=1.9.0 (from pyensembl)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting datacache>=0.4.19 (from pyensembl)
Collecting numpy>=1.7 (from pyensembl)
  Using cached numpy-1.14.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting serializable (from pyensembl)
Collecting tinytimer (from pyensembl)
Collecting gtfparse>=0.0.3 (from pyensembl)
Collecting memoized-property>=1.0.2 (from pyensembl)
Collecting typechecks>=0.0.2 (from pyensembl)
Collecting python-dateutil>=2 (from pandas>=0.15->pyensembl)
  Using cached python_dateutil-2.7.1-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas>=0.15->pyensembl)
  Using cached pytz-2018.3-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from datacache>=0.4.19->pyensembl)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting biopython>=1.65 (from datacache>=0.4.19->pyensembl)
  Using cached biopython-1.70-cp36-cp36m-manylinux1_x86_64.whl
Collecting requests>=2.5.1 (from datacache>=0.4.19->pyensembl)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting mock (from datacache>=0.4.19->pyensembl)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting progressbar33>=2.4 (from datacache>=0.4.19->pyensembl)
Collecting simplejson (from serializable->pyensembl)
Collecting idna<2.7,>=2.5 (from requests>=2.5.1->datacache>=0.4.19->pyensembl)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.5.1->datacache>=0.4.19->pyensembl)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.5.1->datacache>=0.4.19->pyensembl)
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.5.1->datacache>=0.4.19->pyensembl)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock->datacache>=0.4.19->pyensembl)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, pytz, numpy, pandas, appdirs, biopython, idna, urllib3, certifi, chardet, requests, pbr, mock, progressbar33, typechecks, datacache, simplejson, serializable, tinytimer, gtfparse, memoized-property, pyensembl
Erreur de segmentation (core dumped)




________________________________
De : Alex Rubinsteyn <notifications@github.com>
Envoyé : jeudi 22 mars 2018 19:30
À : openvax/pyensembl
Cc : HansCeril; Comment
Objet : Re: [openvax/pyensembl] Installing Ensembl release fails at reading GTF step (#195)


Hi Hans,

I'm guessing your issue is unrelated to the failure above. I've never seen a segmentation fault from installing pyensembl. Can you tell me more about your setup (what OS, version of Python, &c). Also, can you paste a more complete error message (including any preceding lines that might give a clue about what is segfaulting where).
